import ProfileBadges from './ProfileBadges';
import ProfileBadgesProvider from './ProfileBadgesProvider';
import ProfileLevel from '../ProfileLevel/ProfileLevel';

/**
 * Everything RGG contributes to the Profile page's additional-profile-fields slot.
 *
 * The level and the earned-accomplishments boxes are two separate cards but ship as
 * ONE widget: the slot registration is generated by tutor-contrib-rgg into
 * env.config.jsx, so a second entry there would mean a tutor-plugin change and MFE
 * re-install for no user-visible difference. Rendering both here also pins their
 * order -- level above accomplishments -- rather than leaving it to slot
 * priorities. They share the single QueryClientProvider.
 */
const ProfileGamificationSection = () => (
  <ProfileBadgesProvider>
    <ProfileLevel />
    <ProfileBadges />
  </ProfileBadgesProvider>
);

export default ProfileGamificationSection;
